<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>Preview</LangVersion>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <RuntimeIdentifier>linux-x64</RuntimeIdentifier>    
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gtk4DotNet\Gtk4DotNet.csproj" />
  </ItemGroup>

  <!-- <ItemGroup>
    <EmbeddedResource Include="resources/resources.gresource">
      <LogicalName>app.gresource</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="cd resources&#xD;&#xA;glib-compile-resources resources.xml" />
  </Target> -->

  <ItemGroup>
    <EmbeddedResource Include="./resources/builder.ui">
      <LogicalName>builder</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/alertdialogbuilder.ui">
      <LogicalName>alertdialogbuilder</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/dialogbuilder.ui">
      <LogicalName>dialogbuilder</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/buildersubclass.ui">
      <LogicalName>buildersubclass</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/windowsubclass.ui">
      <LogicalName>windowsubclass</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/adwwindowsubclass.ui">
      <LogicalName>adwwindowsubclass</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/customcolumnview.ui">
      <LogicalName>customcolumnview</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/windowwebviewsubclass.ui">
      <LogicalName>windowwebviewsubclass</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/progress.ui">
      <LogicalName>progress</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/menu.ui">
      <LogicalName>menu</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/headerbar.ui">
      <LogicalName>headerbar</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/custombox.ui">
      <LogicalName>custombox</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/style.css">
      <LogicalName>style</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/listviewstyle.css">
      <LogicalName>listviewstyle</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/progressstyle.css">
      <LogicalName>progressstyle</LogicalName>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="./resources/image.jpg">
      <LogicalName>image</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
