<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>library</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<Version>8.1.2</Version>
	<FileVersion>8.1.2</FileVersion>
	<AssemblyVersion>8.1.2</AssemblyVersion>
	<AssemblyName>Gtk4DotNet</AssemblyName>
	<Authors>Uwe Riegel</Authors>
	<Company>Uwe Riegel</Company>		
	<Description>.NET 10 Bindings for GTK 4, functional declarative similar to REACT or Kotlin Compose</Description>
	<PackageLicenseUrl></PackageLicenseUrl>
	<PackageProjectUrl>https://github.com/uriegel/Gtk4DotNet</PackageProjectUrl>
	<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
	<PackageLicenseFile>LICENSE</PackageLicenseFile>
	<PackageTags>DotNet;.NET;C#;CSharp;Gtk4;Gtk;Linux;P/Invoke</PackageTags>
	<PackageReleaseNotes>ListView, ColumnView</PackageReleaseNotes>
	<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	<PackageReadmeFile>README.md</PackageReadmeFile>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<GenerateDocumentationFile>true</GenerateDocumentationFile>
	<NoWarn>1591</NoWarn>
	<LangVersion>Latest</LangVersion>
  </PropertyGroup>

<PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
</PropertyGroup>

<ItemGroup>
    <None Include="..\LICENSE" Pack="true" PackagePath="" />
    <None Include="..\README.md" Pack="true" PackagePath="\" />
</ItemGroup>

<ItemGroup>
  <PackageReference Include="CsTools" Version="8.0.1" />
</ItemGroup>  

</Project>
