<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Version>9.0.32-beta</Version>
    <AssemblyName>Gtk4DotNet</AssemblyName>
    <Authors>Uwe Riegel</Authors>
    <Company>Uwe Riegel</Company>		
    <Description>.NET 10 Bindings for GTK 4</Description>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl>https://github.com/uriegel/Gtk4DotNet</PackageProjectUrl>
    <PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageTags>DotNet;.NET;C#;CSharp;Gtk4;Gtk;Linux;P/Invoke</PackageTags>
    <PackageReleaseNotes></PackageReleaseNotes>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>1591</NoWarn>
    <LangVersion>Latest</LangVersion>
  </PropertyGroup>

  <PropertyGroup>
      <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
      <None Include="..\LICENSE" Pack="true" PackagePath="" />
      <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CsTools" Version="9.0.1" />
  </ItemGroup>  

</Project>
